# Generated by Django 2.2.13 on 2020-06-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200630_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='rubruc',
            new_name='rubric',
        ),
    ]
