# Generated by Django 2.2.13 on 2020-07-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20200630_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='entries', to='bboard.Rubric', verbose_name='Рубрика'),
        ),
    ]
