# Generated by Django 2.2.13 on 2020-07-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20200716_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbSlave',
            fields=[
                ('bb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bboard.Bb')),
                ('slave_mark', models.IntegerField()),
            ],
            bases=('bboard.bb',),
        ),
    ]
