# Generated by Django 2.2.13 on 2020-07-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_bbslave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BbSlave',
        ),
    ]
