# Generated by Django 2.2.13 on 2020-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
